services:
  - type: web
    name: hrms-lite-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: hrms_lite
      - key: CORS_ORIGINS
        sync: false
